# Generated by Django 3.1.1 on 2020-10-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_iscomplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='answers',
            field=models.TextField(default=0),
        ),
    ]
