# Generated by Django 3.1.1 on 2020-10-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_curent_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='curent_question',
            field=models.IntegerField(default=1),
        ),
    ]
