# Generated by Django 3.1.1 on 2020-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201006_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='answers',
            field=models.TextField(default=''),
        ),
    ]
