# Generated by Django 3.1.2 on 2020-10-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201006_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='curent_test',
            field=models.IntegerField(default=1),
        ),
    ]
