# Generated by Django 3.1.1 on 2021-05-17 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_time_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_begin',
            field=models.DateField(default=datetime.date(2021, 5, 17)),
        ),
    ]
