# Generated by Django 3.1.1 on 2021-05-17 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_arh', '0002_auto_20201011_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(default=1)),
                ('TimeToTest', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='test_arh.test'),
        ),
    ]
